/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

public class Project02 {
    public static void main(String[] args) throws Exception {
        
        int head = 1;
        int next = 2;
        int aux;
        int sum = 0;

        while(head<4000000) {
            aux = next;
            next = next+head;
            head = aux;

            if(head%2==0) {
                sum += head;
            }
        }

        System.out.println(sum);
    }
}
